[www]
user = www-data
group = www-data

; Par defaut php-fpm ecoute sur un socket local, uniquement joignable
; depuis l'interieur du meme container. On le fait ecouter sur le port 9000
; de toutes les interfaces pour que nginx (un autre container) puisse s'y connecter.
listen = 0.0.0.0:9000

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
